name: Lint

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci # or yarn install
      - uses: Cyb3r-Jak3/html5validator-action
        with:
          root: tests/
          blacklist: invalid